### PR TITLE
Initial draft of recommendations on CDNs

### PR DESCRIPTION
**Pull request by davidfurey**
## What does this change?

Adds some recommendations on using CDNs. I don't think this is documented elsewhere.  I suspect there is a lot more useful info we could include but this seems like a reasonable starting point.

Please do question these recommendations if you disagree if them.

### CODE REVIEW

**Review by akash1810 — COMMENTED** [review]
Should we also recommend [Fastly shielding](https://docs.fastly.com/en/guides/shielding)?

**Review by philmcmahon — COMMENTED** [review]
Add sections on shielding/logging

**Comment by philmcmahon** [comment]
Looks great to me. Following @akash1810 's suggestion I've added a shielding bit. Have also put a section on logging in - might be overkill but it comes up fairly frequently. 

Feel free to suggest/make any changes

**Comment by davidfurey** [comment]
Thanks Phil.  I've added a note about IAM for logging

**Review by akash1810 — APPROVED** [review]

**Pull request merged**
