### PR TITLE
docs: How to deploy CloudFormation with Riff-Raff

### PR DESCRIPTION
**Pull request by akash1810**
## What is being recommended?
The @guardian/devx-operations team have been tracking tag usage across the estate as part of the tagging obligation, where resources should have the `Stack`, `Stage`, `App`, and `gu:repo` tags.

Deploying infrastructure with Riff-Raff is the fastest way to follow the obligation. Add documentation for how to deploy a CloudFormation stack with Riff-Raff.

> [!TIP]
> Easiest to view these changes in [their rendered form](https://github.com/guardian/recommendations/blob/aa/riff-raff-cfn/continuous-deployment-of-cloudformation.md).

### CODE REVIEW

**Comment by JuliaBrigitte** [comment]
How will people end up reading this file, is is linked to from somewhere?

Should the doc link more prominently to the cdk documentation?

**Comment by akash1810** [comment]
> How will people end up reading this file, is is linked to from somewhere?

Great question! The only place I can think of right now is the [Obligatron dashboard](https://metrics.gutools.co.uk/d/cdokcsudhxrswa/obligatron?orgId=1). Suggestions welcomed though!

> Should the doc link more prominently to the cdk documentation?

Can do! I'm unsure of the benefits however; could you elaborate? Any suggestions on how/where welcomed too.

**Review by AshCorr — APPROVED** [review]
Nice 👌

**Comment by akash1810** [comment]
Merging. I'll try to find a volunteer to run through these instructions with, and raise additional PRs if needed.

**Pull request merged**
